version: '3.1'
services:
  web:
    restart: always
    image: odoo16-prod
    container_name: prueba1
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/usr/lib/python3/dist-packages/odoo/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - HOST=ps13-prueba1
    secrets:
      - postgresql_password
  db:
    restart: always
    image: postgres:13
    container_name: ps13-prueba1
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass

